name: Denopendabot
on:
  schedule:
    - cron: "0 0 * * *" # modify to your convinient time
  workflow_dispatch:
    
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: hasundue/denopendabot@0.5.10 # @denopendabot hasundue/denopendabot
        with:
          token: ${{ steps.generate_token.outputs.token }}
          user-token: ${{ steps.generate_token.outputs.token }}